### ISSUE TITLE
Some minor changes

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/bls-keygen-app#1]
WOW! great stuff! Few comments...

Here we should probably use a phrase as an example instead of `password`
<img width="756" alt="Screen Shot 2020-03-09 at 19 03 53" src="https://user-images.githubusercontent.com/16929357/76264672-dd607c00-6238-11ea-8157-39001302c6a5.png">

This page should have a button `generate again` or something so you can continually generate more keys without having to `go back`
<img width="778" alt="Screen Shot 2020-03-09 at 19 03 58" src="https://user-images.githubusercontent.com/16929357/76264689-e9e4d480-6238-11ea-9660-dbd7c721daee.png">

looks like a stray angle bracket on the top left. Also add a space in the title
<img width="482" alt="Screen Shot 2020-03-09 at 19 06 30" src="https://user-images.githubusercontent.com/16929357/76264785-1c8ecd00-6239-11ea-9d78-7a3b607ffca9.png">

Any chance the keystore encryption process has a callback to the percentage completed? Would be awesome to show how much time is left (as a percent). otherwise looks great!
<img width="758" alt="Screen Shot 2020-03-09 at 19 08 08" src="https://user-images.githubusercontent.com/16929357/76264856-58c22d80-6239-11ea-9bae-ab523cc07142.png">

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek , i have pushed changes for all of your issues except for the one about the encryption percentage callback.  I have not seen anything in bls-keystore's encrpytion function that has a pecentage callback, but I think this is potentially a good idea.  Perhaps there something else that we can use to estimate the time it would take to encrypt the keystore and then use that number as a benchmark for the progress/percentage counter?

**Comment by mpetrunic** [comment]
We don't have percentage callback, I'm not sure it makes sense since generation takes ~100ms so you won't be able to see loading anyways afaik
