### ISSUE TITLE
Hex string prefix

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/bls-keygen-app#2]
Hey strings like public/private key should have `0x` prefix

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic there aren't any hex strings currently displayed in the app.  The master key is the output of a Uint8Array, and doesn't need to be pre-fixed with a hex, as far as I know.

**Comment by mpetrunic** [comment]
Well all keys will be Uint8Array, I would say it makes sense to display master key as hex as it's expected for Uint8Arrays to be displayed as hex on UI

**Comment by 3xtr4t3rr3str14l** [comment]
this has been implemented in 
https://github.com/ChainSafe/bls-keygen-app/commit/e1b301babca876080e96d76a450d8bed7f61834f

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic can this issue be closed?
