### ISSUE TITLE
Display derivation path

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/bls-keygen-app#4]
You could display derivation path (`m/12381/3600/0/0`) alongside master key.

**Comment by 3xtr4t3rr3str14l** [comment]
this is now displayed in the export validator keys page in https://github.com/ChainSafe/bls-keygen-app/commit/e1b301babca876080e96d76a450d8bed7f61834f

**Comment by mpetrunic** [comment]
Probably, I think you need to update and commit lockfile so it get's deployed

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic you should be able to see the deployed changes now

**Comment by mpetrunic** [comment]
You removed travis file, so it's now getting deployed at all.

I don't see anything new here: https://modest-spence-2de182.netlify.com/

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic I can see the changes at that URL.  maybe try clearing your cache?
