### ISSUE TITLE
Ability to generate child keys with different use

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/bls-keygen-app#5]
Example:
![image](https://user-images.githubusercontent.com/8836210/76292148-f277f200-62ae-11ea-9b45-6ef497155314.png)

**Comment by 3xtr4t3rr3str14l** [comment]
I added functionality in https://github.com/ChainSafe/bls-keygen-app/commit/e1b301babca876080e96d76a450d8bed7f61834f to allow the user to select which validator index they want to use to export the validator keys

**Comment by mpetrunic** [comment]
Seems like you removed travis file, so it's not deploying at all now. Cannot see this functionality

**Comment by mpetrunic** [comment]
Seems like you removed travis file, so it's not deploying at all now. Cannot see this functionality

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic I can see the changes here https://modest-spence-2de182.netlify.com/.  maybe clear your cache?

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic to be sure though, you can only make validator keys with a different index, for now.

**Comment by mpetrunic** [comment]
Oh, I just figured it's after you click on "export validator keys". 

Maybe it would be more user friendly if under master key you would choose validator index and had button to export, which would lead you to page with password inputs. Users could see that regenerating master key changesvalidator keys (so app really updated keys on master regen). Just a suggestion
