### ISSUE TITLE
Make this mainnet-proof

### ISSUE THREAD

**Issue by q9f** [ChainSafe/bls-keygen-app#7]
> Also, maybe recommend users to clone it, and run it offline? Can it run offline?

I strongly agree here. I would do it like MyCrypto does: Not allowing the handling of private keys on the website unless users download it to their computer.

Also, for testnet this is fine, but if people really intend to use this on mainnet, they will loose their private keys. Even though it's crystal clear for you and me, the average users does not understand what it means to manage your own key and how important backups are.

So, after looking at it from an _average user_ perspective, you should rearrange the workflow on that website:

1. Click that generate button (or restore from mnemonic)
2. Immediately ask for a password to encrypt the private key
3. Ask to confirm the password
4. Force the user to download the encrypted keys
5. Display everything else after these steps ^ are completed

**Comment by 3xtr4t3rr3str14l** [comment]
@q9f the changes for this issue have been deployed to master and can be found here:
https://bls-keygen.com/

The way we decided to approach this is a little different than what you outlined above, but I believe that it achieves the desired result.  Any and all feedback welcome, of course.
